name: Lists
description: "A modern list app with multiple lists, category filtering, and price tracking in EUR/USD. Features smooth animations, dark/light themes, and drag-and-drop reordering."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_slidable: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.0
  url_launcher: ^6.3.1
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
